version: "3.9"

services:
  chat-server:
    build:
      context: ./server
    container_name: messencharles-server
    ports:
      - "3000:3000"
    restart: unless-stopped

  chat-client:
    build:
      context: ./client
    container_name: messencharles-client
    ports:
      - "8080:8080"
    depends_on:
      - chat-server
